name = "AtomsCalculatorsUtilities"
uuid = "9855a07e-8816-4d1b-ac92-859c17475477"
authors = ["Teemu JÃ¤rvinen <teemu.j.jarvinen@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsCalculators = "a3e0e189-c65a-42c1-833c-339540406eb1"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NeighbourLists = "2fcf5ba9-9ed4-57cf-b73f-ff513e316b9c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AtomsBase = "0.3"
AtomsCalculators = "0.1.2"
Bumper = "0.6"
ChunkSplitters = "2"
Folds = "0.2.10"
NeighbourLists = "0.5.6"
StrideArrays = "0.1"
Unitful = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
